data_source_txt:
  dobson:
    path: "\\ad.pmodwrc.ch\\Institute\\Departments\\WRC\\OZONE\\A_Dobsons\\DataPostProcessing\\ProcessedData\\Level1\\051\\CalL01"
    level: "Level1"
    device_1: 
        name: "051"
        calibration: "CalL01"
    device_2: 
      name: "062"
      calibration: "CalL01"
    device_3:
      name: "101"
      calibtarion: "CalL01"

      
  brewer:
    path: "\\ad.pmodwrc.ch\\Institute\\Departments\\WRC\\OZONE\\B_Brewer\\DataPostProcessing\\ProcessedData\\Level1"
    level: "Level1"
    device_1:
      name: "040"
      calibtarion: "CalL01"
    
    device_2:
      name: "072"
      calibtarion: "CalL01"
    
    device_3:
      name: "156"
      calibtarion: "CalL01"

    device_1:
      name: "163"
      calibtarion: "CalL01"


