brewer:
  devices: ["040","072","156","163"]
  path: "\\\\ad.pmodwrc.ch\\Institute\\Departments\\WRC\\OZONE\\B_Brewer\\DataPostProcessing\\ProcessedData"
  save_path: "\\\\ad.pmodwrc.ch\\Institute\\Departments\\WRC\\OZONE\\B_Brewer\\DataPostProcessing\\ProcessedData"
  key : "Brewer"
  header:
  - Type
  - Time(UTC)
  - Temp
  - Airmass
  - Ozone
  - Ozone_error
  - SO2
  - SO2_error
  - Flag
  level: Level1

  
dobson:
  devices: ["051","062","101"] 
  key : "Dobson"
  level: Level1
  path: "\\\\ad.pmodwrc.ch\\Institute\\Departments\\WRC\\OZONE\\A_Dobsons\\DataPostProcessing\\ProcessedData"
  header : ["iii", 
          "t",  
          "yyyymmdd",
          "ss",
          "tt",
          "timeC",
          "rvalC",
          "sdevC",
          "timeD",
          "rvalD",
          "sdevD",
          "timeA",
          "rvalA",
          "sdevA",
          "flag1",
          "flag2",
          "flag3",
          "muC",
          "muD",
          "muA",
          "OzC",
          "OzD",
          "OzA",
          "OzAD",
          "OzCD",
          "OzAC"]